export { hasDoxygenHeader } from './hasDoxygenHeader'
export { hasMacroNameInMend } from './hasMacroNameInMend'
export { hasMacroParentheses } from './hasMacroParentheses'
export { lineEndings } from './lineEndings'
export { noNestedMacros } from './noNestedMacros'
export { strictMacroDefinition } from './strictMacroDefinition'
export { hasRequiredMacroOptions } from './hasRequiredMacroOptions'
